// components/Movie.tsx
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { AppDispatch } from "../store/Store";
import { getMovies, saveMovie, updateMovie, deleteMovie } from "../reducers/MovieSlice";
import { MovieModel } from "../models/MovieModel";

function Movie() {
    const dispatch = useDispatch<AppDispatch>();
    const movies = useSelector((state) => state.movies);

    useEffect(() => {
        dispatch(getMovies());
    }, [dispatch]);

    const [name, setName] = useState("");
    const [year, setYear] = useState("");
    const [image, setImage] = useState<File | null>(null);
    const [isEditing, setIsEditing] = useState(false);
    const [editId, setEditId] = useState("");

    const handleAdd = () => {
        if (!name || !year || !image) {
            alert("All fields are required!");
            return;
        }
        const newMovie = new MovieModel("", name, year, image); // ID will be auto-generated by backend
        dispatch(saveMovie(newMovie));
        resetForm();
    };

    const handleEdit = (movie: MovieModel) => {
        setName(movie.name);
        setYear(movie.year);
        setImage(movie.image);
        setEditId(movie.id);
        setIsEditing(true);
    };

    const handleUpdate = () => {
        if (!name || !year || !image) {
            alert("All fields are required!");
            return;
        }
        const updatedMovie = new MovieModel(editId, name, year, image);
        dispatch(updateMovie({ id: editId, movie: updatedMovie }));
        resetForm();
    };

    const handleDelete = (id: string) => {
        dispatch(deleteMovie(id));
    };

    const resetForm = () => {
        setName("");
        setYear("");
        setImage(null);
        setIsEditing(false);
    };

    return (
        <div
            style={{ backgroundImage: `url(${backgroundImage})` }}
            className="min-h-screen bg-cover bg-center"
        >
            <Navbar />

            <div className="p-6 bg-opacity-0 bg-white rounded-lg mx-auto max-w-screen-xl mt-10">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
                    <input
                        type="text"
                        name="name"
                        placeholder="Name"
                        value={name}
                        onChange={(e) => setName(e.target.value)}
                        className="p-3 border border-gray-300 rounded bg-transparent text-white text-sm w-full h-10"
                    />
                    <input
                        type="text"
                        name="year"
                        placeholder="Year"
                        value={year}
                        onChange={(e) => setYear(e.target.value)}
                        className="p-3 border border-gray-300 rounded bg-transparent text-white text-sm w-full h-10"
                    />
                    <input
                        type="file"
                        name="image"
                        onChange={(e) => setImage(e.target.files ? e.target.files[0] : null)}
                        className="p-3 border border-gray-300 rounded bg-transparent text-white text-sm w-full h-10"
                    />
                </div>

                {/* Conditionally render Add/Update button */}
                <div className="mb-4 flex space-x-4">
                    {isEditing ? (
                        <>
                            <button
                                onClick={handleUpdate}
                                className="bg-blue-500 text-white px-4 py-2 rounded"
                            >
                                Update
                            </button>
                            <button
                                onClick={handleCancel}
                                className="bg-gray-500 text-white px-4 py-2 rounded"
                            >
                                Cancel
                            </button>
                        </>
                    ) : (
                        <button
                            onClick={handleAdd}
                            className="bg-orange-500 text-white px-4 py-2 rounded"
                        >
                            Add
                        </button>
                    )}
                </div>

                {/* Table takes up full width */}
                <table className="min-w-full bg-transparent divide-y divide-gray-500">
                    <thead>
                    <tr className="bg-gray-100 bg-opacity-0">
                        <th className="py-2 text-white">ID</th>
                        <th className="py-2 text-white">Name</th>
                        <th className="py-2 text-white">Year</th>
                        <th className="py-2 text-white">Image</th>
                        <th className="py-2 text-white">Actions</th>
                    </tr>
                    </thead>
                    <tbody className="space-y-4">
                    {customers.map((customer: CustomerModel) => (
                        <tr key={customer.year} className="rounded-lg">
                            <td className="border px-4 py-2 text-orange-400 rounded-l-xl">{customer.id}</td>
                            <td className="border px-4 py-2 text-white">{customer.name}</td>
                            <td className="border px-4 py-2 text-white">{customer.year}</td>
                            <td className="border px-4 py-2 text-white">{customer.image?.name}</td>
                            <td className="border px-4 py-2 flex justify-center space-x-2 rounded-r-xl">
                                <button
                                    onClick={() => handleEdit(customer)}
                                    className="bg-yellow-500 text-white p-2 rounded"
                                >
                                    <FaEdit />
                                </button>
                                <button
                                    onClick={() => handleDelete(customer.year)}
                                    className="bg-red-500 text-white p-2 rounded"
                                >
                                    <FaTrash />
                                </button>
                            </td>
                        </tr>
                    ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
}

export default Movie;
